name: CI
on: [push]

jobs:
  sast-scan:
    name: Run Bandit Scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      
      - name: Install python & setup
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install bandit
        run: pip install Bandit 

      - name: Run Bandit
        run: bandit -ii -ll -r . 
      
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: bandit-findings
          path: bandit-report.json
      
